### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by ghost** [mmenestret/fp-ressources#9]
There is a typo in the repository headline: `Functional programming great ressources` to `Functional programming great resources`.

Once #8 is merged, I think we don't need the following branches anymore: `reorg-articles` and `to-read`. Thus, we can delete them.

**Comment by mmenestret** [comment]
Thanks ! Fixed the headline.
About the branches, I'll delete `to-read`, the `reorg-articles` was the beginning of my work to close #7 which you fixed on your side as well. I'll check which one is the best cause I made some reorganization (some parts are redundant), merging and deletion !

**Comment by mmenestret** [comment]
I deleted to-read, thanks for the issue :)
